### ISSUE TITLE
Data Saturday Denmark

### ISSUE THREAD

**Issue by brianbonk** [dataplat/DataSaturdays#374]
### eventname

Data Saturday Denmark

### date

2023-03-25 09:00:00 -00:00

### description

Data Saturday Denmark is a free one-day event for professionals who use the Microsoft data platform. This community event offer content across data management, cloud and hybrid architecture, analytics, business intelligence, AI, and `more.<br><br>The` community revolves around Microsoft Data Platform and Cloud (SQL Server, Power BI, Synapse, Azure, PowerShell, etc), but we invite other topics as well (other cloud vendors, interesting technologies).<br><br>At this point, we are not able to cover any travel/accommodation expenses.<br><br>The event is a free in-person event.

### scheduleurl

https://sessionize.com/api/v2/ztilolfa/view/GridSmart

### speakerlisturl

https://sessionize.com/datasatdk23

### organizers

Jens Vestergaard;https://twitter.com/vestergaardj;jv@t-sql.dk,Brian Bønk Rueløkke;https://twitter.com/brbonk;brianbonk@gmail.com,Mathias Halkjær Petersen;https://twitter.com/HalkjaerM;halkjaer@live.dk

**Comment by SQLDBAWithABeard** [comment]
Yo @brianbonk - If you need to update your event - please update this yaml file 
https://github.com/dataplat/DataSaturdays/blob/main/_data/events/datasaturday0032.yml 

and raise a PR instead of a new event :-)

I have fixed this one for you - It looks like you have not announced your schedule in sessionize yet - Is that correct?
